version: 2

updates:
  - package-ecosystem: pip
    directory: /
    groups:
      python:
        patterns:
          - "*"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7

  - package-ecosystem: github-actions
    directory: /
    groups:
      actions:
        patterns:
          - "*"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
