// Copyright 2022-2023 Quarkslab
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * @file DataType.h
 *
 * Functions and classes related to data types
 */

#ifndef QUOKKA_COMPOSITE_DATA_H
#define QUOKKA_COMPOSITE_DATA_H

#include <concepts>
#include <cstddef>
#include <cstdint>
#include <functional>
#include <iterator>
#include <memory>
#include <optional>
#include <ranges>
#include <string>
#include <type_traits>
#include <utility>
#include <variant>
#include <vector>

// clang-format off: Compatibility.h must come before ida headers
#include "Compatibility.h"
// clang-format on
#include <pro.h>
#include <typeinf.hpp>

#include "absl/container/flat_hash_map.h"
#include "absl/hash/hash.h"

#include "Bucket.h"
#include "ProtoHelper.h"  // Kept for ProtoHelper
#include "ProtoWrapper.h"
#include "Reference.h"
#include "Util.h"

// #if IDA_SDK_VERSION < 850
// #include "api_v8/DataType_v8.h"
// #else
// #include "api_v9/DataType_v9.h"
// #endif

namespace quokka {

struct type_uid_t {
  bool is_real_tid;  // Is it IDA tid or ours?
  tid_t tid;         // Either IDA assigned or auto-generated by us
  auto operator<=>(const type_uid_t&) const = default;

  template <typename H>
  friend H AbslHashValue(H h, const type_uid_t& m) {
    return H::combine(std::move(h), m.is_real_tid, m.tid);
  }
};

type_uid_t GetTypeUid(const tinfo_t& tif);
type_uid_t GetTypeUid(const tid_t& tid);

/**
 * Base type of data. It does not strictly match the protobuf one
 */
enum BaseType : uint8_t {
  TYPE_UNK = 0,
  TYPE_B,
  TYPE_W,
  TYPE_DW,
  TYPE_QW,
  TYPE_OW,
  TYPE_FLOAT,
  TYPE_DOUBLE,
  TYPE_VOID,
  TYPE_POINTER,
  TYPE_ARRAY,
  TYPE_STR,
  TYPE_ALIGN,
};

BaseType GetBaseType(const tinfo_t& flags);
BaseType GetBaseType(flags_t flags);

constexpr bool IsPrimitiveType(BaseType t) {
  return t == TYPE_UNK || t == TYPE_B || t == TYPE_W || t == TYPE_DW ||
         t == TYPE_QW || t == TYPE_OW || t == TYPE_FLOAT || t == TYPE_DOUBLE ||
         t == TYPE_VOID;
}

/**
 * -----------------------------------------------------------------------------
 * quokka::CompositeTypeMember
 * -----------------------------------------------------------------------------
 * A member of a composite type.
 */
class CompositeTypeMember {
 public:
  CompositeTypeMember(ea_t o, std::string&& n, BaseType t, asize_t sz)
      : offset(o), name(std::forward<std::string>(n)), size(sz) {
    type = t == TYPE_ALIGN ? TYPE_UNK : t;
  }

  ea_t offset;       ///< Field offset (IDA internal)
  std::string name;  ///< Name of the field
  BaseType type;     ///< Base type of the value
  std::optional<type_uid_t>
      target_tuid;  ///< ID of the target type (one of DataTypes variant)
  asize_t size;     ///< Size of the field
  std::vector<const Reference*> xref_to;
};

/**
 * -----------------------------------------------------------------------------
 * quokka::CompositeType
 * -----------------------------------------------------------------------------
 * Base class representing a generic composite data type.
 *
 * A composite data type might contain heterogeneous members.
 */
class CompositeType : public ProtoHelper {
 public:
  CompositeType(std::string&& n, tid_t id_, size_t sz)
      : name(std::forward<std::string>(n)), id(id_), size(sz) {}

  std::string name;  ///< Composite type name
  tid_t id;          ///< Type id (IDA internal)
  size_t size;       ///< Structure size
  std::string
      c_str;  ///< C-string representation of the composite type (if any)
  std::vector<CompositeTypeMember> members;  ///< Members list
  std::optional<std::variant<type_uid_t, BaseType>>
      element_type;  ///< The element type (only for pointer and array)
  mutable std::vector<const Reference*> xref_to;
};

/**
 * -----------------------------------------------------------------------------
 * quokka::StructureType
 * -----------------------------------------------------------------------------
 * A class representing a structure data type in IDA.
 */
class StructureType : public CompositeType {
 public:
  template <typename... ArgsT>
  StructureType(ArgsT&&... Args)
      : CompositeType(std::forward<ArgsT>(Args)...) {}
};

/**
 * -----------------------------------------------------------------------------
 * quokka::UnionType
 * -----------------------------------------------------------------------------
 * A class representing a union data type in IDA.
 */
class UnionType : public CompositeType {
 public:
  template <typename... ArgsT>
  UnionType(ArgsT&&... Args) : CompositeType(std::forward<ArgsT>(Args)...) {}
};

/**
 * -----------------------------------------------------------------------------
 * quokka::PointerType
 * -----------------------------------------------------------------------------
 * A class representing a pointer type in IDA.
 */
class PointerType : public CompositeType {
 public:
  template <typename... ArgsT>
  PointerType(ArgsT&&... Args) : CompositeType(std::forward<ArgsT>(Args)...) {}
};

/**
 * -----------------------------------------------------------------------------
 * quokka::ArrayType
 * -----------------------------------------------------------------------------
 * A class representing an array type in IDA.
 */
class ArrayType : public CompositeType {
 public:
  template <typename... ArgsT>
  ArrayType(ArgsT&&... Args) : CompositeType(std::forward<ArgsT>(Args)...) {}
};

struct EnumValue {
  std::string name;
  int64_t value;
  std::vector<const Reference*> xref_to;
};

/**
 * -----------------------------------------------------------------------------
 * quokka::EnumType
 * -----------------------------------------------------------------------------
 * Base class representing a enum defined in the program.
 * @note Two EnumType are considered equal if they have the same name
 */
class EnumType : public ProtoHelper {
 public:
  EnumType(std::string n) : name(std::move(n)) {}

  std::string name;               ///< Name of the enum
  std::vector<EnumValue> values;  ///< Internal values of the enum
  mutable std::vector<const Reference*> xref_to;
  std::string c_str;  ///< C-string representation of the enum (if any)

  bool operator==(const EnumType& o) const noexcept {
    return this->name == o.name;
  }

  /**
   * Hash implementation of the object using absl::Hash
   * @tparam H Hash
   * @param h Hash value
   * @param m EnumType object
   * @return An hash value for the object
   */
  template <typename H>
  friend H AbslHashValue(H h, const EnumType& m) {
    return H::combine(std::move(h), m.name);
  }
};

template <typename T>
constexpr Quokka::CompositeType::CompositeSubType CompositeSubTypeToProto() {
  using U = std::remove_cvref_t<T>;
  if constexpr (std::is_same_v<U, UnionType>)
    return Quokka_CompositeType_CompositeSubType_TYPE_UNION;
  else if constexpr (std::is_same_v<U, StructureType>)
    return Quokka_CompositeType_CompositeSubType_TYPE_STRUCT;
  else
    static_assert(false, "Mismatch between the CompositeSubTypes");
}

class DataTypes {
 public:
  using TypeT =
      std::variant<StructureType, UnionType, EnumType, PointerType, ArrayType>;
  using CollectionT = absl::flat_hash_map<type_uid_t, std::unique_ptr<TypeT>>;

 private:
  CollectionT collection;

  template <bool IsConst>
  class value_iterator {
    template <bool>
    friend class value_iterator;
    friend class DataTypes;

    using BaseIt =
        std::conditional_t<IsConst, typename CollectionT::const_iterator,
                           typename CollectionT::iterator>;
    using MappedRef = std::conditional_t<IsConst, const TypeT&, TypeT&>;
    using PairRef = std::pair<const type_uid_t&, MappedRef>;

    struct arrow_proxy {
      PairRef value;
      const PairRef* operator->() const noexcept { return &value; }
    };

   public:
    using iterator_concept = std::forward_iterator_tag;
    using iterator_category = std::forward_iterator_tag;
    using difference_type =
        typename std::iterator_traits<BaseIt>::difference_type;
    using value_type = std::pair<type_uid_t, TypeT>;
    using reference = PairRef;
    using pointer = arrow_proxy;

    value_iterator() = default;

    // Allow conversion: iterator -> const_iterator
    value_iterator(const value_iterator<false>& other)
      requires IsConst
        : it_(other.it_) {}

    reference operator*() const {
      assert(it_->second && "null TypeT pointer in DataTypes::collection");
      return {it_->first, *it_->second};
    }

    pointer operator->() const {
      assert(it_->second && "null TypeT pointer in DataTypes::collection");
      return pointer{operator*()};
    }

    value_iterator& operator++() {
      ++it_;
      return *this;
    }

    value_iterator operator++(int) {
      value_iterator tmp = *this;
      ++(*this);
      return tmp;
    }

    friend bool operator==(const value_iterator& a, const value_iterator& b) {
      return a.it_ == b.it_;
    }

    friend bool operator!=(const value_iterator& a, const value_iterator& b) {
      return !(a == b);
    }

   private:
    explicit value_iterator(BaseIt it) : it_(it) {}
    BaseIt it_{};
  };

  template <class T>
  friend auto operator|(DataTypes& dt, filter_type_adaptor_t<T>);

  template <class T>
  friend auto operator|(const DataTypes& dt, filter_type_adaptor_t<T>);

  explicit DataTypes() = default;  ///< Private constructor

 public:
  using iterator = value_iterator<false>;
  using const_iterator = value_iterator<true>;

  iterator begin() { return iterator{collection.begin()}; }
  iterator end() { return iterator{collection.end()}; }

  const_iterator begin() const { return const_iterator{collection.begin()}; }
  const_iterator end() const { return const_iterator{collection.end()}; }

  const_iterator cbegin() const { return const_iterator{collection.cbegin()}; }
  const_iterator cend() const { return const_iterator{collection.cend()}; }

  /**
   * Return the instance of the `DataTypes` class.
   * Used for the singleton pattern.
   * @return `DataTypes`
   */
  static DataTypes& GetInstance() {
    static DataTypes instance;
    return instance;
  }

  /**
   * Delete constructors for singleton pattern
   */
  DataTypes(DataTypes const&) = delete;
  DataTypes(DataTypes&&) = delete;
  void operator=(DataTypes const&) = delete;
  void operator=(DataTypes&&) = delete;

  /**
   * Creates the object of type T and pushes into the collection.
   *
   * @tparam T The type of the object to store. Must be a type from
   * TypeT
   * @tparam Args Arguments to be forwarded to the T constructor
   * @param tuid The type uid of the type
   * @param args Arguments of the T constructor
   * @return A reference to the newly added object
   */
  template <is_one_of_variant_v<TypeT> T, typename... ArgsT>
  T& emplace(type_uid_t tuid, ArgsT&&... args) {
    auto p = std::make_unique<TypeT>(std::in_place_type<T>,
                                     std::forward<ArgsT>(args)...);
    return std::get<T>(
        *(collection.insert({std::move(tuid), std::move(p)}).first->second));
  }

  /**
   * Adds the object T to the collection.
   *
   * @tparam T The type of the object to store. Must be a type from
   * TypeT
   * @param tuid The ID of the type
   * @param obj object to push into the collection
   * @return A reference to the newly added object
   */
  template <is_one_of_variant_v<TypeT> T>
  const T& insert(type_uid_t tuid, T&& obj) {
    using U = std::remove_cvref_t<T>;
    auto p =
        std::make_unique<TypeT>(std::in_place_type<U>, std::forward<T>(obj));
    return std::get<T>(
        *(collection.insert({std::move(tuid), std::move(p)}).first->second));
  }

  /**
   * Find the type corresponding to the specified tid.
   * @return An iterator to the requested element. If no such element is found,
   * past-the-end (see end()) iterator is returned.
   */
  const_iterator find_by_tuid(const type_uid_t& tuid) const {
    return const_iterator{collection.find(tuid)};
  }

  size_t size() const { return collection.size(); }
};

// Concepts and helpers
template <typename T, typename U = std::remove_cvref_t<T>>
concept IsCompositeType =
    std::is_same_v<U, StructureType> || std::is_same_v<U, UnionType>;

template <typename T>
auto operator|(DataTypes& dt, filter_type_adaptor_t<T>) {
  return dt.collection | std::views::filter([](auto& it) {
           return it.second && std::holds_alternative<T>(*it.second);
         }) |
         std::views::transform([](auto& it) {
           return std::pair<decltype((it.first)), T&>{it.first,
                                                      std::get<T>(*it.second)};
         });
}

template <typename T>
auto operator|(const DataTypes& dt, filter_type_adaptor_t<T>) {
  return dt.collection | std::views::filter([](const auto& it) {
           return it.second && std::holds_alternative<T>(*it.second);
         }) |
         std::views::transform([](const auto& it) {
           return std::pair<decltype((it.first)), const T&>{
               it.first, std::get<T>(*it.second)};
         });
}

template <typename F, typename T>
concept visit_callback =
    std::invocable<F&, T&> || std::invocable<F&, const type_uid_t&, T&>;

template <typename... Ts, typename Variant, typename F>
  requires((is_one_of_variant_v<Ts, Variant>) && ...)
void visit_selected(Variant&& v, F&& fn) {
  std::visit(
      [&]<typename U>(U&& x) {
        using X = std::remove_cvref_t<U>;
        if constexpr ((std::same_as<X, Ts> || ...)) {
          std::invoke(std::forward<F>(fn), std::forward<U>(x));
        }
      },
      std::forward<Variant>(v));
}

template <typename... Ts, typename DT, typename F>
  requires std::same_as<std::remove_cvref_t<DT>, DataTypes> &&
           ((visit_callback<F, std::conditional_t<
                                   std::is_const_v<std::remove_reference_t<DT>>,
                                   const Ts, Ts>>) &&
            ...)
static inline void for_each_visit(DT&& dt, F&& fn) {
  for (auto&& [tid, var] : dt) {
    visit_selected<Ts...>(var, [&](auto&& x) {
      if constexpr (std::invocable<F&, decltype(x)>) {
        std::invoke(fn, std::forward<decltype(x)>(x));
      } else if constexpr (std::invocable<F&, decltype((tid)), decltype(x)>) {
        std::invoke(fn, tid, std::forward<decltype(x)>(x));
      } else {
        static_assert(always_false_v<decltype(x)>,
                      "for_each_visit: callback signature mismatch");
      }
    });
  }
}

inline size_t GetTinfoSize(const tinfo_t& tif) {
  size_t size;
  return (tif.is_forward_decl() || (size = tif.get_size()) == BADADDR ? 0
                                                                      : size);
}

/**
 * Export the composite data types of the program.
 *
 * Will populate the `CompositeTypes` singleton container.
 * This is usually fast because not many structures are defined in a program.
 */
void ExportCompositeDataTypes();

/**
 * Export all the enums defined in the program
 */
void ExportEnums();

type_uid_t ExportPointer(const tinfo_t& tif);

type_uid_t ExportArray(const tinfo_t& tif);

}  // namespace quokka

#endif  // QUOKKA_COMPOSITE_DATA_H
