name: doc
on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "bindings/python/**"
      - "mkdocs.yml"
      - "pyproject.toml"
      - "setup.py"
      - "doxygen.cfg"
      - "README.md"
      - ".github/workflows/doc.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  deploy-doc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          pip install '.[doc]'
          sudo apt-get update && sudo apt-get install --yes doxygen
      - name: Deploy doc
        run: mkdocs gh-deploy --force
